[settings]
python.uv_venv_auto = true
experimental = true
idiomatic_version_file_enable_tools = ["swift"]

[tools]
java = "temurin-24"
"ubi:ll-nick/leadr" = "latest"
doggo = "latest"
node = "latest"
rust = "latest"
