theme = "rose_pine"

[editor]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "â”Š"
render = true
skip-levels = 1

[editor.statusline]
left = ["mode", "file-name", "spinner", "read-only-indicator", "file-modification-indicator"]
right = [
    "diagnostics",
    "selections",
    "register",
    "file-type",
    "file-line-ending",
    "position",
]

[editor.statusline.mode]
insert = "INS"
normal = "NOR"
select = "SEL"
