module_separator = " "
reset_color = false

[bookmarks]
search_depth = 100
exclude = []

#[[module]]
#type = "Symbol"
#symbol = " "
# = "Blue"
#color.TrueColor = [196, 167, 231]

[[module]]
type = "Bookmarks"
separator = " "
#color = "Magenta"
color.TrueColor = [246, 193, 119]
behind_symbol = "⇡"
surround_with_quotes = false

[[module]]
type = "Commit"
max_length = 24
empty_text = ""
surround_with_quotes = false

[[module]]
type = "State"
separator = " "

[module.conflict]
disabled = false
text = "(CONFLICT)"
color = "Red"

[module.divergent]
disabled = false
text = "(DIVERGENT)"
color = "Cyan"

[module.empty]
disabled = false
text = "(EMPTY)"
color = "Yellow"

[module.immutable]
disabled = false
text = "(IMMUTABLE)"
color = "Yellow"

[module.hidden]
disabled = false
text = "(HIDDEN)"
color = "Yellow"

[[module]]
type = "Metrics"
template = "[{changed} {added}{removed}]"
color = "Magenta"

[module.changed_files]
prefix = ""
suffix = ""
#color = "Cyan"
color.TrueColor = [196, 167, 231]

[module.added_lines]
prefix = "+"
suffix = ""
#color = "Green"
color.TrueColor = [49, 116, 143]

[module.removed_lines]
prefix = "-"
suffix = ""
color.TrueColor = [235, 111, 146]
#color = "Red"

